<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Balaji" failures="1" tests="5" name="automation_test" time="0.157" errors="0" timestamp="2021-06-02T12:25:46 IST">
  <testcase classname="com.selenium.listener.SampleTestClass" name="testFour" time="0.019">
    <skipped/>
  </testcase> <!-- testFour -->
  <testcase classname="com.selenium.listener.SampleTestClass" name="testGetData" time="0.002"/>
  <testcase classname="com.selenium.listener.SampleTestClass" name="testGetData" time="0.004"/>
  <testcase classname="com.selenium.listener.SampleTestClass" name="testOne" time="0.006"/>
  <testcase classname="com.selenium.listener.SampleTestClass" name="testThree" time="0.006">
    <failure type="java.lang.AssertionError" message="expected [7] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [7] but found [5]
at com.selenium.listener.SampleTestClass.testThree(SampleTestClass.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testThree -->
</testsuite> <!-- automation_test -->
